### ISSUE TITLE
Error when trying to sync the highlights

### ISSUE THREAD

**Issue by wenlzhang** [weichenw/obsidian-hypothesis-plugin#1]
I got the following error messages when trying to sync the highlights into Obsidian:
```
Uncaught (in promise) TypeError: Cannot read property '2' of undefined
    at eval (eval at <anonymous> (app.js:1), <anonymous>:2:128829)
    at Array.reduce (<anonymous>)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:2:128552)
    at et.startSync (eval at <anonymous> (app.js:1), <anonymous>:2:128958)
    at async at.startSync (eval at <anonymous> (app.js:1), <anonymous>:2:131252)
```

Re-starting Obsidian did not resolve the issue either.

**Comment by yuvve** [comment]
Same here!

```
Uncaught (in promise) TypeError: Cannot read property 'exact' of undefined
    at eval (eval at <anonymous> (app.js:1), <anonymous>:2:128833)
    at Array.reduce (<anonymous>)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:2:128552)
    at et.startSync (eval at <anonymous> (app.js:1), <anonymous>:2:128958)
    at async at.startSync (eval at <anonymous> (app.js:1), <anonymous>:2:131252)
```

**Comment by weichenw** [comment]
Hi all, I have updated the plugin to process annotations without associations to any highlights. I am not sure how did that happen. I managed to find public annotation examples where I think the annotations were imported somehow. I can see it anywhere in the official API docs.

You probably need to adjust the template if you only want to show annotations.

I only use the extension to highlight then add annotations to the highlight. I hope this fix covers some of the different usages.

![image](https://user-images.githubusercontent.com/9876456/138040922-18306c8d-681f-4ac7-bc3a-cb4cdf91e757.png)

Thanks

**Comment by wenlzhang** [comment]
> Otherwise, you have to reset the history, delete all the synced files. Then when you sync again, it will recreate everything again.

Is it possible to only re-sync a specific file, instead of deleting all synced files first and syncing all files again?

The sync mechanism reminds me of two Readwise-related plugins:

- [readwiseio/obsidian-readwise: Official Readwise plugin for Obsidian](https://github.com/readwiseio/obsidian-readwise)
- [jsonMartin/readwise-mirror](https://github.com/jsonMartin/readwise-mirror)

The first one mainly works as follows:

- If a file exists already in Obsidian, only new highlights are appended at the end of the file/note when executing the sync command
- If a file is deleted from Obsidian, one can manually force re-syncing this specific file on the Readwise website.
  - After that, one can execute the sync command in Obsidian.
  - Then, this specific (deleted) file would be re-created, with all old and new highlights included.
  - For all other (existing) files in Obsidian, only new highlights would be appended to the end of the corresponding files.

The second one just mirrors/downloads all old and new highlights to Obsidian.
