### ISSUE TITLE
Highlights from  local PDF file don't sync

### ISSUE THREAD

**Issue by natarslan** [weichenw/obsidian-hypothesis-plugin#12]
It would be amazing to be able to sync the highlights from a local PDF. I know you wrote "Have not tested to sync annotations on PDFs." so I tested it. The highlights show in hypothes.is webpage but they are not syncing to Obsidian vault. Do you think there is a way to fix this?

**Comment by weichenw** [comment]
I have not catered it for local PDF. However, it is stored in hypothes.is webpage, there are some missing attributes. Unfortunately, it requires a bit of rework to make this work, and I will look at it in the near future.

**Comment by pandichef** [comment]
Is there any update on this?  I noticed that it also breaks with public websites that are missing attributes and I've run into this situation a few times now.  Is there a way to set a default here so it fails gracefully? e.g., just pull raw text data into Obsidian

**Comment by weichenw** [comment]
no I am unable to replicate this issue unfortunately
