### ISSUE TITLE
Recognize files based on Front Matter instead of file name

### ISSUE THREAD

**Issue by silic0n64** [weichenw/obsidian-hypothesis-plugin#13]
As this plugin is inspired by [Obsidian Kindle Plugin](https://github.com/hadynz/obsidian-kindle-plugin), I think it is good to post the idea here.

As of the new update of Obsidian Kindle Plugin, the plugin recognizes the files based on front matter data,instead of filenames, this gives extra advantages, for example: we can move files anywhere in the vault and also rename, still the plugin recognizes the file.

But in the hypothes.is plugin, we can't move or rename the files. If we do, the plugin thinks the item is deleted (Command: resync deleted files confirms that) and shows it on the deleted list. So, I think recognizing files based on metadata should be more convenient for most users.

**Comment by weichenw** [comment]
I will look into this

**Comment by phgn0** [comment]
@weichenw have you started on this yet? If not, I'm very interested in helping to get this to work!

**Comment by phgn0** [comment]
Update: I took a stab at the frontmatter file matching, please see https://github.com/weichenw/obsidian-hypothesis-plugin/pull/39. It's working nicely for me locally!
