### ISSUE TITLE
can't initiate first sync

### ISSUE THREAD

**Issue by wastemobile** [weichenw/obsidian-hypothesis-plugin#14]
After install and enter API Token, can't initiate first sync, just nothing happened.

<img width="552" alt="hypothes" src="https://user-images.githubusercontent.com/451223/140613255-9df5e329-c4b0-44f9-b49a-7f31845fbd6b.png">

**Comment by weichenw** [comment]
> After install and enter API Token, can't initiate first sync, just nothing happened.
> 
> <img alt="hypothes" width="552" src="https://user-images.githubusercontent.com/451223/140613255-9df5e329-c4b0-44f9-b49a-7f31845fbd6b.png">

Hi, which version are you using? It seems like your hypothesis highlight does not have a title.

**Comment by wastemobile** [comment]
Thanks!

My hypothes library did have some old and weird annotations, I went to delete those items and sync work!

Sorry for the inconvenience.
