### ISSUE TITLE
Bug: created and updated fields not being filled

### ISSUE THREAD

**Issue by swehba** [weichenw/obsidian-hypothesis-plugin#15]
The {{created}} and {{updated}} fields never appear to be filled. Do they depend on information from the article or is the time of the import used? If the former, is it possible that none of the articles I have been highlighting have this information? If that is so, then this is not a bug, but it would be nice to fill these in with the current timestamp if not provided by the article. Cheers.

**Comment by weichenw** [comment]
Those 2 fields are coming from the timestamps captured by Hypothesis against the highlights/annotations.

![image](https://user-images.githubusercontent.com/9876456/141211741-48f1b8ec-cc9f-4ab4-97cd-931579eb3255.png)

![image](https://user-images.githubusercontent.com/9876456/141211798-32aa0bea-9189-46b3-936e-4517eb28e13d.png)

I hope this make sense
