### ISSUE TITLE
File name cannot be created correctly if it contains :

### ISSUE THREAD

**Issue by wenlzhang** [weichenw/obsidian-hypothesis-plugin#18]
For instance, if a file name is `File: A`, then the created note would be `File`, i.e. everything after `:` would be omitted. As a result, if there would be a new file called `File: B`, then all highlights corresponding to `File: B` would be synced into `File` as well.

Therefore, it would be great if special symbols like `:` would be handled properly. For instance, symbols like `:` can be replaced by `_` or spaces.

**Comment by weichenw** [comment]
Good pick up. I will look into it

**Comment by weichenw** [comment]
This is fixed now. Simply just use sanitize filename package to do its thing.

eg: Semicolons: When & 'how' to use them (with examples) -> Semicolons When & how to use them (with examples)

**Comment by wenlzhang** [comment]
It seems that symbols like # and | cannot be removed correctly. These symbols are not supported when trying to insert files as note links whose name contain these symbols.

Therefore, is it possible to remove/replace all symbols that are not supported by Obsidian as file names?

**Comment by weichenw** [comment]
> It seems that symbols like # and | cannot be removed correctly. These symbols are not supported when trying to insert files as note links whose name contain these symbols.
> 
> Therefore, is it possible to remove/replace all symbols that are not supported by Obsidian as file names?

Fixed this in 0.1.10

Unfortunately, I used a package that sanitize the filename for OS. Anything obsidian specific to obsidian has to be coded on top of that.
