### ISSUE TITLE
Sync different hypothesis groups in different vaults/folders?

### ISSUE THREAD

**Issue by woodae99** [weichenw/obsidian-hypothesis-plugin#22]
Hi, **This is not an issue**
Firstly, thank you so much for this plugin - it's a huge help to myself and my students.
When collaborating in hypothesis you can create different groups, say for a research dissertation and another for, perhaps crisis management - I was wondering if it is possible to have those groups sync to specific folders or different vaults in obsidian. 
for e.g. my critical research students collaborate on a group but use different vaults for other modules and hypothesis groups.
Hope this makes sense!
Thanks again
C

**Comment by weichenw** [comment]
> Hi, **This is not an issue** Firstly, thank you so much for this plugin - it's a huge help to myself and my students. When collaborating in hypothesis you can create different groups, say for a research dissertation and another for, perhaps crisis management - I was wondering if it is possible to have those groups sync to specific folders or different vaults in obsidian. for e.g. my critical research students collaborate on a group but use different vaults for other modules and hypothesis groups. Hope this makes sense! Thanks again C

Saving to a different vault is definitely not doable. The quickest way is to bring is group, you can create it as a tag and link them.

![image](https://user-images.githubusercontent.com/9876456/145663504-4a9c161a-d832-44bf-b367-d5c1dc6c4d69.png)

**Comment by weichenw** [comment]
You can have the same article in 'private' and a different group with different highlights. I will need to think about it.

At the moment, I brought in the group as a tag against individual highlights.

**Comment by woodae99** [comment]
That's great, thanks - that should help.
FYI, I came across this https://jonudell.info/h/facet (https://web.hypothes.is/help/how-do-i-export-my-annotations/) demo export tool that allows a number of permutations by group, tags, users etc. Not sure if you've come across it, or if it's any help with the above question. 
I don't know how it might be possible, but my non-programmer brain imagines something like:
For Vault "a", specify user API token and groups to include = x + y ...
For Vault "b", specify uer API token and groups to include = z
I need to send you a coffee or 3!

**Comment by weichenw** [comment]
@woodae99 I have added a button that allows you to add/remove groups synced. By default, all groups are selected. Please remember, highlights previously synced will not be removed if you remove a particular group. It only takes comes into effect the next highlights sync.

![image](https://user-images.githubusercontent.com/9876456/146381726-0aa82dc7-e577-47aa-80f8-b1d1d9b95a79.png)

![image](https://user-images.githubusercontent.com/9876456/146381753-58cdb2e5-2be1-4f4d-9aa8-3fad14f18c07.png)

**Comment by weichenw** [comment]
Splitting them into folders, I will think about it next time after I added the frontmatters

**Comment by woodae99** [comment]
Awesome, thanks!
