### ISSUE TITLE
How to Sync in scheduled time

### ISSUE THREAD

**Issue by chenyukang** [weichenw/obsidian-hypothesis-plugin#23]
For example, 3 minutes sync one time.

**Comment by weichenw** [comment]
There is no scheduler support at this point of time.

**Comment by chenyukang** [comment]
> There is no scheduler support at this point of time.

If I implement this, would you like to merge it?
From my use case, my Obsidian will not restart in several days, I think it will be good if there is an option to sync automatically in several hours.
