### ISSUE TITLE
Creation date as backlink

### ISSUE THREAD

**Issue by Mirtma** [weichenw/obsidian-hypothesis-plugin#24]
Is it possible to have the creation date as backlink [[YYYY-MM-DD]] in a template, so that my daily note would show it at linked mentions?

**Comment by weichenw** [comment]
You will have to change the date format. Then adjust the nunjuck template to use [[{{highlight.created}}]]

![image](https://user-images.githubusercontent.com/9876456/146382887-ca431eee-034d-411b-b5b2-2c173616f14b.png)

**Comment by Mirtma** [comment]
Hello,
thank you for your reply! But I can't get it to work. It always shows me
the date and link to the article. Where exactly should I insert that
variable?

Kind regards,
Matjaž


V V čet., 16. dec. 2021 ob 14:43 je oseba Wei Chen ***@***.***>
napisala:

**Comment by Mirtma** [comment]
I only get these:

[image: image.png]

V V čet., 16. dec. 2021 ob 15:01 je oseba Matjaž ***@***.***>
napisala:

**Comment by weichenw** [comment]
> mage: image.png]

Hi, can reattach the image? Doesn't seem to load

**Comment by Mirtma** [comment]
Of course!

V V pet., 17. dec. 2021 ob 12:40 je oseba Wei Chen ***@***.***>
napisala:

**Comment by weichenw** [comment]
For whatever reason, image is not getting attached

**Comment by Mirtma** [comment]
Well, it shows that instead of creation date it only shows [[]] where the
date should be.

**Comment by Mirtma** [comment]
![Zajeta slika](https://user-images.githubusercontent.com/2010414/146632850-42f2b350-149c-4c4f-a8d9-6ea7c180fef7.JPG)

**Comment by weichenw** [comment]
try the nunjuck template below;

```
{% if is_new_article %}# {{title}}

## Metadata
{% if author %}- Author: [{{author}}]({{authorUrl}}){% endif %}
- Title: {{title}}
{% if url %}- Reference: {{url}}{% endif %}
- Category: #article{% endif %}

{% if is_new_article -%}## Highlights{%- endif %}
{% for highlight in highlights -%}- {{highlight.text}} — Created on [[{{highlight.created}}]], [Updated on {{highlight.updated}}]({{highlight.incontext}}) {% if 'Private' != highlight.group %} — Group: #{{highlight.group| replace(" ", "-")}}{%- endif %}
{% if highlight.tags | length %}   - Tags: {% for tag in highlight.tags -%} #{{tag | replace(" ", "-")+" "}}{%- endfor %}{%- endif %}
{% if highlight.annotation %}   - Annotation: {{highlight.annotation}}{%- endif -%}{%- endfor -%}
```

**Comment by Mirtma** [comment]
Thank you! Now it shows as I want.

Kind regards,
Matjaž

V V sob., 18. dec. 2021 ob 14:51 je oseba Wei Chen ***@***.***>
napisala:
