### ISSUE TITLE
Dataview compatibility metadata

### ISSUE THREAD

**Issue by javiavid** [weichenw/obsidian-hypothesis-plugin#29]
I'm trying to create 2 metadata fields with the creation and update date that is compatible with dataview, but I can't. 
Could you help me?

**Comment by weichenw** [comment]
Can you please show me what you configured in the template?

**Comment by javiavid** [comment]
The result is that Created and Updated are empty.
Thanks




{% if is_new_article %}---
{% if author %}Author: [{{author}}]({{authorUrl}}){% endif %}
Title: {{title}}
{% if url %}URL: {{url}}{% endif %}
Tags: #article{% endif %}
Created: {{highlight.created}}
Updated: {{highlight.updated}}
Status: 
---


{% if is_new_article -%}## Highlights{%- endif %}
{% for highlight in highlights -%}- {{highlight.text}} — [Updated on {{highlight.updated}}]({{highlight.incontext}})
{% if highlight.tags | length %}   - Tags: {% for tag in highlight.tags -%}#{{tag| replace(" ", "-")}} {%- endfor %}{%- endif %}
{% if highlight.annotation %}   - Annotation: {{highlight.annotation}}{%- endif -%}{%- endfor -%}

**Comment by weichenw** [comment]
Unfortunately, that is now how it works. The timestamps are against the highlight and not the article. That's how it is stored in hypothesis itself.

![image](https://user-images.githubusercontent.com/9876456/148939965-65e4df5a-f3b3-49cc-bc0e-83c6ad1c431e.png)

**Comment by javiavid** [comment]
I'd really like to get the highlight timestamps, but they come up empty.
Is the template wrong?
