### ISSUE TITLE
Highlights don't respect the original text's order of appearance (like on Hypothesis' side pane)

### ISSUE THREAD

**Issue by Pyrodusk** [weichenw/obsidian-hypothesis-plugin#30]
See screenshots : 
![image](https://user-images.githubusercontent.com/80559262/149446725-32ede1ed-7a51-4176-aa3f-1192c26df6bd.png)
![image](https://user-images.githubusercontent.com/80559262/149446580-c1c5a9fd-9e62-419a-b4f2-6671b7b8e10e.png)

What I am referring is the same thing as the "sort top-level annotations by" setting in this [prototype built by a member of the Hypothesis team](https://jonudell.info/h/facet/) when set to "document location".

Notes: 
- The same happens to all my notes.
- I tried deleting all notes and resync them but the result is the same.

**Comment by weichenw** [comment]
I have fixed it in 0.1.15
Before:
![image](https://user-images.githubusercontent.com/9876456/151106018-a9d6cc96-599c-40e2-ac3b-ce1355bd4faa.png)

After:
![image](https://user-images.githubusercontent.com/9876456/151106035-0d8f8ee4-6fac-46b6-9be4-6fe1e8edd6ef.png)

Give it a try and see if it works on your end..

**Comment by weichenw** [comment]
> See screenshots : ![image](https://user-images.githubusercontent.com/80559262/149446725-32ede1ed-7a51-4176-aa3f-1192c26df6bd.png) ![image](https://user-images.githubusercontent.com/80559262/149446580-c1c5a9fd-9e62-419a-b4f2-6671b7b8e10e.png)
> 
> What I am referring is the same thing as the "sort top-level annotations by" setting in this [prototype built by a member of the Hypothesis team](https://jonudell.info/h/facet/) when set to "document location".
> 
> Notes:
> 
> * The same happens to all my notes.
> * I tried deleting all notes and resync them but the result is the same.


I have fixed it in 0.1.15
Before:
![image](https://user-images.githubusercontent.com/9876456/151106018-a9d6cc96-599c-40e2-ac3b-ce1355bd4faa.png)

After:
![image](https://user-images.githubusercontent.com/9876456/151106035-0d8f8ee4-6fac-46b6-9be4-6fe1e8edd6ef.png)

Give it a try and see if it works on your end..

**Comment by Pyrodusk** [comment]
Thank you for your time, I tested the update but sadly it's not exactly what I was talking about. I saw you modified it to sort highlights by dates but what I meant was to be able to have them sorted by their location in the web page they are from. That way no matter when you highlight new elements in the page, when you do a first sync (or delete and re sync), it will respect the location of each highlight in the web page thus giving better contextual meaning in my opinion.

**Comment by weichenw** [comment]
> Thank you for your time, I tested the update but sadly it's not exactly what I was talking about. I saw you modified it to sort highlights by dates but what I meant was to be able to have them sorted by their location in the web page they are from. That way no matter when you highlight new elements in the page, when you do a first sync (or delete and re sync), it will respect the location of each highlight in the web page thus giving better contextual meaning in my opinion.

Unfortunately, I am not bringing in the positions at this point in time. I get what you mean, but unfortunately, it is too much work to update the existing document as the sequence of highlights in a document can happen in any position and any given day.

**Comment by temberature** [comment]
I think maybe changing some logic can handle this with small effort, detail as follow:
perhaps the code can rewrite the whole file (one page file) associating with the updated page from last sync time.

**Comment by temberature** [comment]
after I read Api docs, I find it a little more complicated, there isn't page retrieving, it only can be implemented by processing annotation information.
https://h.readthedocs.io/en/latest/api-reference/v1/#tag/annotations/paths/~1search/get

**Comment by nhan000** [comment]
I so want this to be implemented :(
