### ISSUE TITLE
Better support for multiple-line notes

### ISSUE THREAD

**Issue by wenlzhang** [weichenw/obsidian-hypothesis-plugin#33]
It would be great if the multiple-line notes can be synced as sub list items, to better style multiple-line notes.

**The note:**
```
First line
Second line
```

**The desired synced note:** (This is also the Readwise Official plugin handles multiple-line notes.)
```
- [ ] First line
    - Second line
```

**The template:**
```
{% if is_new_article %}# {{title}}

{% if is_new_article %}## Metadata{% endif %}

{% if is_new_article %}{% if author %}- Author:: [{{author}}]({{authorUrl}}){% endif %}
- Title:: {{title}}
- Category Hypothesis:: Article{% endif %}
{% if url %}- Source URL:: {{url}}{% endif %}{% endif %}

{% if is_new_article %}## Highlights{% endif %}

{% for highlight in highlights %}> {{highlight.text}} (View Highlight [{{highlight.location}}]({{highlight.incontext}})) ^hs{{highlight.id}}{% if highlight.tags | length %}
- Tag: {% for tag in highlight.tags %}#{{tag| replace(" ", "-")}} {% endfor %}{% endif %}{% if highlight.annotation %}
- [ ] {{highlight.annotation}}{% endif %}{% if highlight.created %}
- Highlighted on {{highlight.created}}{% endif %}{% if highlight.updated %}
- Updated on {{highlight.updated}}{% endif %}

{% endfor %}
```

**Comment by phgn0** [comment]
BTW, I got multi-line highlights and annotations to look a bit nicer by using `{{highlight.text | replace("\n", " ")}}` instead of `{{highlight.text}}`. Just a simple fix in the template.

**Comment by wenlzhang** [comment]
> BTW, I got multi-line highlights and annotations to look a bit nicer by using `{{highlight.text | replace("\n", " ")}}` instead of `{{highlight.text}}`. Just a simple fix in the template.

Thanks for this!

Similar to the other issue, I was meant to say that the template I pasted there did not give me the desired results. **Therefore, it would be great if this proposal can be supported.**
