### ISSUE TITLE
No highlights/annotations are synced after installation (web not pdf) 

### ISSUE THREAD

**Issue by ahmed316dev** [weichenw/obsidian-hypothesis-plugin#40]
The integration works just fine, however, annotations and highlights are not detected 
![image](https://user-images.githubusercontent.com/26268158/158625797-31d11922-f29b-41be-a4f3-87f91f87ef62.png)

even tho I have 10 highlights and annotations in my Hypothesis.is
![image](https://user-images.githubusercontent.com/26268158/158625997-7d25e6a2-72c4-4cb8-8249-49946aafc2d2.png)

the plugin detects my groups no problem, but it just doesn't detect the content
![image](https://user-images.githubusercontent.com/26268158/158626180-58673c80-6735-4322-ae44-9bd364b01cdf.png)

It's worth mentioning I tried restarting Obsidian, tried reconnecting the API, but to no avail

**Comment by temberature** [comment]
VM137:2 Error syncing 2021-06-12: Folder Indexer, Smarter Typography, & OCR Error: ENOENT: no such file or directory, open 'Z:\pdfnotes\hypothesis\obsidianroundup.org\2021-06-12 Folder Indexer, Smarter Typography, & OCR.md'

may because of this

**Comment by weichenw** [comment]
Try updating to the latest version and try again.

**Comment by ahmed316dev** [comment]
for some reason, the plugin won´t update on Obsidian, i tried uninstalling and reinstalling, restarted Obsidian, no dice

**Comment by ahmed316dev** [comment]
![screenshot - 94d4y8P4](https://user-images.githubusercontent.com/26268158/159285418-1c3bbe1d-5fec-438c-b397-49d0ec70f4ee.gif)

**Comment by ahmed316dev** [comment]
I even tried sideloading the release, Obsidian still recognize it as 0.1.16

**Comment by weichenw** [comment]
I have deleted and recreated 0.1.17. Can you please try again?
---
Wei Chen Wong // ***@***.***
