### ISSUE TITLE
sync conflict using Obsidian Git plugsin in combination with Obsidian Hypothes.is plugin

### ISSUE THREAD

**Issue by Hopsakee** [weichenw/obsidian-hypothesis-plugin#47]
I get a sync error everytime I start up Obsidian if I have both plugins enabled.
The error is in the file obsidian-hypothesis-plugin\data.json.

It concerns the following line:
  "lastSyncDate": "2022-04-08T04:20:14.319Z"

Could it be the case that the hypothesis plugin syncs just before de git plugin?
If so, it could maybe be solved if there was an option for the hypothesis plugin to start about 30s after startup of Obsidian.

**Comment by weichenw** [comment]
Maybe try deleting everything and resync everything again.

**Comment by Hopsakee** [comment]
Thanks that worked.
