### ISSUE TITLE
[Feature request] Ability to mirror highlights, in the same order as on the page

### ISSUE THREAD

**Issue by yep-dev** [weichenw/obsidian-hypothesis-plugin#50]
In my workflow, highlights order is very important as it gives context to other highlights - crucial for long articles.
As I am aware that preserving order and existing edits is technically challenging, it's more of a mirror workflow, like https://github.com/jsonMartin/readwise-mirror . I don't edit those mirrored files, just reference them by persistent highlight id at the end.

Hypothesis is one of the few platforms that allow for extracting this order through the API.
![Screenshot 2022-05-19 at 14 24 04](https://user-images.githubusercontent.com/69042276/169292522-7fc3e06d-c83b-46fe-9503-07dbab5002d2.png)
Readwise makes use of it in https://github.com/readwiseio/obsidian-readwise, but it has many issues of its own and is an unnecessary intermediary.

So, it would be great if you could implement following story:
- User selects "Ordered mirror mode" in the options
On sync:
- Folder with highlights is deleted
- Highlights are inserted as usual, but ordered based on the position in the API, from the lowest start position to the highest

**Comment by duxrat** [comment]
I did some dirty changes to allow mirroring by deleting highlights before sync if someone is interested: https://github.com/yep-dev/obsidian-hypothesis-plugin/commit/67624d09a5284b9e3bda93d67971b0fd9d6fb383
